# Generated by Django 6.0.5 on 2026-05-29 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infants_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PHM', 'PHM'), ('PARENT', 'Parent')], max_length=10)),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('rag_chunks_used', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(choices=[('EN', 'English'), ('SI', 'Sinhala'), ('TA', 'Tamil')], default='EN', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('infant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_logs', to='infants_module.infant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
