# Generated by Django 6.0.5 on 2026-05-27 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_module', '0002_moh_officer_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infant',
            fields=[
                ('phn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_weight_kg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('birth_length_cm', models.DecimalField(decimal_places=1, max_digits=4)),
                ('birth_order', models.PositiveSmallIntegerField()),
                ('moh_division', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_phm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_infants', to='accounts_module.phm_user')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
