# Generated by Django 6.0.5 on 2026-05-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0002_moh_officer_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='push_subscription',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='phm_user',
            name='push_subscription',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
