# Generated by Django 6.0.5 on 2026-05-27 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infants_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('NORMAL', 'Normal'), ('MAM', 'Moderate Acute Malnutrition Risk'), ('SAM', 'Severe Acute Malnutrition Risk')], max_length=10)),
                ('confidence_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('prob_normal', models.DecimalField(decimal_places=4, max_digits=5)),
                ('prob_mam', models.DecimalField(decimal_places=4, max_digits=5)),
                ('prob_sam', models.DecimalField(decimal_places=4, max_digits=5)),
                ('feature_snapshot', models.JSONField()),
                ('model_version', models.CharField(default='bluecradle_lstm_v1', max_length=50)),
                ('triggered_by_growth_record', models.PositiveIntegerField()),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('infant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessments', to='infants_module.infant')),
            ],
            options={
                'ordering': ['-assessed_at'],
                'unique_together': {('infant', 'triggered_by_growth_record')},
            },
        ),
    ]
