# Generated by Django 6.0.5 on 2026-05-27 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_module', '0002_moh_officer_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FHBAtomicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moh_division', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('NEW_REGISTRATION', 'New Infant Registration'), ('GROWTH_RECORD', 'Anthropometric Measurement'), ('VACCINATION', 'Vaccination Administered'), ('DEFAULTER', 'Vaccination Defaulter'), ('POSTNATAL_VISIT', 'Domiciliary Postnatal Visit'), ('CONTRAINDICATION', 'Vaccine Contraindicated')], max_length=25)),
                ('fhb_service_code', models.CharField(choices=[('NEW_REG', 'New Registration'), ('GM_ATTENDANCE', 'Growth Monitoring Attendance'), ('EPI_VACCINATION', 'EPI 3/79 Register Entry'), ('MISSED_CLINIC', 'Missed Clinic / Domiciliary Follow-up'), ('POSTNATAL_10', 'Postpartum Visit — First 10 Days'), ('POSTNATAL_42', 'Postpartum Visit — 42 Days'), ('MALNUTRITION_FLAG', 'Low Birth Weight / Malnutrition Flag')], max_length=25)),
                ('priority', models.CharField(choices=[('CRITICAL_HIGH', 'Critical High — SAM/MAM Alerts'), ('CRITICAL', 'Critical — Vaccinations / Defaulters'), ('STANDARD', 'Standard — Growth Records / Admin')], default='STANDARD', max_length=15)),
                ('payload_json', models.JSONField()),
                ('event_timestamp', models.DateTimeField()),
                ('is_synced', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['priority', 'event_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('age_in_days', models.PositiveIntegerField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('height_cm', models.DecimalField(decimal_places=1, max_digits=4)),
                ('muac_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('bilateral_pitting_oedema', models.BooleanField(default=False)),
                ('whz', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waz', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('haz', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('who_classification', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('MAM', 'Moderate Acute Malnutrition'), ('SAM', 'Severe Acute Malnutrition')], max_length=10, null=True)),
                ('days_since_last_visit', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_delta_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('whz_velocity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['infant', 'visit_date'],
            },
        ),
        migrations.CreateModel(
            name='ImmunizationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.CharField(choices=[('BCG', 'BCG'), ('OPV_0', 'OPV Birth Dose'), ('HEP_B', 'Hepatitis B Birth Dose'), ('PENTA_1', 'Pentavalent 1'), ('PENTA_2', 'Pentavalent 2'), ('PENTA_3', 'Pentavalent 3'), ('OPV_1', 'OPV 1'), ('OPV_2', 'OPV 2'), ('OPV_3', 'OPV 3'), ('PCV_1', 'PCV 1'), ('PCV_2', 'PCV 2'), ('PCV_3', 'PCV 3'), ('ROTA_1', 'Rotavirus 1'), ('ROTA_2', 'Rotavirus 2'), ('MR_1', 'MR 1'), ('JE', 'Live JE'), ('DTP_BOOSTER', 'DTP Booster'), ('OPV_BOOSTER', 'OPV Booster'), ('MR_2', 'MR 2')], max_length=20)),
                ('dose_status', models.CharField(choices=[('ADMINISTERED', 'Administered'), ('DEFAULTED', 'Defaulted'), ('CONTRAINDICATED', 'Contraindicated')], max_length=20)),
                ('date_administered', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('adverse_event_noted', models.BooleanField(default=False)),
                ('adverse_event_detail', models.TextField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('is_defaulter', models.BooleanField(default=False)),
                ('defaulter_days_overdue', models.PositiveIntegerField(blank=True, null=True)),
                ('grace_period_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['infant', 'scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ClinicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('session_type', models.CharField(choices=[('CLINIC', 'Clinic Session'), ('DOMICILIARY', 'Domiciliary Visit')], default='CLINIC', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('moh_division', models.CharField(max_length=100)),
                ('is_synced', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinic_sessions', to='accounts_module.phm_user')),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
    ]
