# Generated by Django 6.0.5 on 2026-05-27 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_module', '0002_moh_officer_parent'),
        ('clinic_module', '0001_initial'),
        ('infants_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhbatomicevent',
            name='infant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atomic_events', to='infants_module.infant'),
        ),
        migrations.AddField(
            model_name='fhbatomicevent',
            name='phm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atomic_events', to='accounts_module.phm_user'),
        ),
        migrations.AddField(
            model_name='fhbatomicevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atomic_events', to='clinic_module.clinicsession'),
        ),
        migrations.AddField(
            model_name='growthrecord',
            name='infant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='growth_records', to='infants_module.infant'),
        ),
        migrations.AddField(
            model_name='growthrecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='growth_records', to='clinic_module.clinicsession'),
        ),
        migrations.AddField(
            model_name='immunizationevent',
            name='infant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='immunization_events', to='infants_module.infant'),
        ),
        migrations.AddField(
            model_name='immunizationevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='immunization_events', to='clinic_module.clinicsession'),
        ),
        migrations.AlterUniqueTogether(
            name='immunizationevent',
            unique_together={('infant', 'vaccine')},
        ),
    ]
