# Generated by Django 6.0.5 on 2026-05-29 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0003_parent_push_subscription_phm_user_push_subscription'),
        ('clinic_module', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsession',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='UPCOMING', max_length=20),
        ),
        migrations.CreateModel(
            name='ClinicSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('session_type', models.CharField(choices=[('CLINIC', 'Clinic Session'), ('DOMICILIARY', 'Domiciliary Visit')], default='CLINIC', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('schedule_mode', models.CharField(choices=[('RECURRING', 'Recurring — First date + frequency'), ('FIXED_DATES', 'Fixed Dates — Exact date list')], max_length=20)),
                ('first_date', models.DateField(blank=True, null=True)),
                ('frequency_weeks', models.PositiveSmallIntegerField(blank=True, help_text='How many weeks between each session (e.g. 4 = monthly)', null=True)),
                ('fixed_dates', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinic_schedules', to='accounts_module.phm_user')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('phm', 'year')},
            },
        ),
        migrations.AddField(
            model_name='clinicsession',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='clinic_module.clinicschedule'),
        ),
    ]
