# Generated by Django 6.0.5 on 2026-05-29 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_module', '0003_clinicsession_status_clinicschedule_and_more'),
        ('infants_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ADMINISTERED', 'Administered'), ('DEFAULTED', 'Defaulted'), ('CONTRAINDICATED', 'Contraindicated')], default='PENDING', max_length=20)),
                ('date_given', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administered_scheduled_vaccines', to=settings.AUTH_USER_MODEL)),
                ('infant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_vaccinations', to='infants_module.infant')),
            ],
            options={
                'ordering': ['due_date'],
                'unique_together': {('infant', 'vaccine_name')},
            },
        ),
    ]
